staticdev/django-pagination-bootstrap

pagination_bootstrap/middleware.py
pagination_bootstrap/templatetags/pagination_tags.py

Django 1.9 Compatibility

---

pagination_bootstrap/middleware.py
pagination_bootstrap/templatetags/pagination_tags.py

Ran the project through 2to3 to make compatible with Python 3

Python 3: run through 2to3

---

.travis.yml
pagination_bootstrap/tests.py
runtests.py

Helps #9
This is an initial integration and incomplete in that the tests.py file
needs to be refactored to run tests under Django’s test suite.

Initial integration for TravisCI

---

pagination_bootstrap/tests.py

This change set allows the import to succeed when regression testing in
Python3.

Python3 compatible StringIO import.

---

README.rst

This is a PR for [my comment](https://github.com/staticdev/django-pagination-bootstrap/pull/19#issuecomment-286045826)

readme: add TEMPLATES value for post-1.8 django versions

---

.pre-commit-config.yaml
codecov.yml
noxfile.py
poetry.lock
pyproject.toml
pytest.ini
runtests.py
src/django_pagination_bootstrap/paginator.py
src/django_pagination_bootstrap/templates/pagination.html
tests/manage.py
tests/test_paginator.py
tests/testapp/__init__.py
tests/testapp/settings.py

Test improvements

---

.github/workflows/tests.yml

Coverage bug

---

.github/workflows/dependabot.yml

Workflow upgrade

---

README.rst
docs/conf.py
mypy.ini
noxfile.py

Fix mypy for nox

---

noxfile.py
poetry.lock
pyproject.toml

Added pygments to dev dependecies and made noxfile complete with all default sessions.
Closes #88

Add pygments to tests session

---

src/django_pagination_bootstrap/middleware.py
tests/test_middleware.py
tests/test_paginator.py

Adds constructor to middleware.
Closes #102

Fix middleware

---

src/django_pagination_bootstrap/templatetags/pagination_tags.py
tests/test_pagination_tags.py

Add test_pagination_tags

---

src/django_pagination_bootstrap/middleware.py
src/django_pagination_bootstrap/templatetags/pagination_tags.py
tests/test_http_request.py
tests/test_middleware.py
tests/test_pagination_tags.py

* 100% coverage.
* Middleware string formating
* Tests refactors
Closes #108

Middleware tests and refactors

---

src/django_pagination_bootstrap/templatetags/pagination_tags.py
tests/test_pagination_tags.py

Test autopaginate

---

codecov.yml
pyproject.toml

Increase to 80% minimum coverage

---

.pre-commit-config.yaml
noxfile.py
poetry.lock
pyproject.toml
tests/manage.py
tests/test_middleware.py
tests/test_pagination_tags.py
tests/test_paginator.py

- Add pep8-naming (N) to .flake8
- Add pep8-naming to dev-deps
- Add pep8-naming to nox pre-commit session
- Remove import-order (I) from .flake8
- Remove flake8-annotations (ANN) from .flake8
- Remove black (BLK) from .flake8
- Remove flake8-annotations from nox
- Add pre-commit local hooks
- Add pre-commit session as a local hook on nox
Closes #129

Flake8 / pre-commit / nox review

---

.gitignore

- add .vscode and .idea folders to .gitignore 
Closes #133

Ignore VSCode and PyCharm settings

---

.darglint
.flake8
src/django_pagination_bootstrap/middleware.py
src/django_pagination_bootstrap/paginator.py
src/django_pagination_bootstrap/templatetags/pagination_tags.py

- Move darglint configuration to .flake8
- Fix darglint messages
- Add DAR003 to .flake8 exceptions
Closes #137

Add darglint

---

.github/workflows/tests.yml
noxfile.py
poetry.lock
pyproject.toml

- Add docs-build session
- Do not install dependencies to Poetry environment from Nox session
- Cache exported requirements in Nox sessions
- Add typeguard dev dependency
Closes #174

Nox refactor

---

.github/workflows/constraints.txt
.github/workflows/tests.yml
poetry.lock

Fix toml enconding

---

.github/release-drafter.yml

Add `help wanted` to Release drafter

---

src/django_pagination_bootstrap/templates/pagination.html

Changed `ifequal` condition to `if` according to Django release notes doc: https://docs.djangoproject.com/en/4.1/releases/4.0/
fix: issue #318

fix: issue #318
